version: "2"
services:
  app:
    image: busybox
    container_name: amadeus_app
    depends_on:
      - "nginx"

  data:
    image: busybox
    container_name: amadeus_data
    volumes:
      - .:/var/www

  nginx:
    image: webcodium/nginx:laravel
    container_name: amadeus_nginx
    volumes_from:
      - data
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: amadeus.test
      NGINX_HTTP_PORT: 80
      NGINX_HTTPS_PORT: 443
      NGINX_CLIENT_MAX_BODY_SIZE: 10m
      NGINX_VHOST_ROOT_DIRECTORY: /var/www
      FASTCGI_URL: php
    depends_on:
      - "php"

  php:
    image: webcodium/php:php7
    container_name: amadeus_php
    volumes_from:
      - data
    working_dir: /var/www
    command: >
            /bin/sh -c "rm -f /etc/php/7.0/mods-available/opcache.ini 
            && /usr/sbin/php-fpm7.0 -F -R"
